name: 'Snack25 Backend Deploy' # 워크플로우 이름

on:
  push:
    branches:
      - main # 메인 브랜치에 push가 되면 deploy jobs 트리거(실행)

jobs:
  deploy-to-ec2-whenever-push-to-main:
    name: 'main 브랜치에 push가 되면 EC2로 배포하는 작업'
    runs-on: ubuntu-latest # 우분투(24.04.2) 환경에서 deploy jobs 실행

    steps:
      - name: Checkout Repository # 1. 레포지토리를 체크아웃
        uses: actions/checkout@v4 # actions/checkout 레포지토리의 v4 버전 사용

      - name: Setup Node.js # 2. Node.js 설정
        uses: actions/setup-node@v4 # actions/setup-node 레포지토리의 v4 버전 사용
        with:
          node-version: '22' # Node.js 버전 22 사용
          run_install: false # 이미 설치되어 있으므로 설치하지 않음

      - name: Setup pnpm # pnpm 설정
        uses: pnpm/action-setup@v4 # pnpm/action-setup 레포지토리의 v4 버전 사용
        with:
          version: '10' # pnpm 버전 10 사용
          run_install: false # 이미 설치되어 있으므로 설치하지 않음

      - name: Cache dependencies # 의존성 캐싱
        uses: actions/cache@v4 # actions/cache 레포지토리의 v4 버전 사용
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .pnpm-store  # pnpm store 디렉토리 추가
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }} # 캐시 키 설정
          restore-keys: |
            ${{ runner.os }}-pnpm- # 캐시 키 복원

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts # 빌드에 필요한 devDependencies도 설치
        env:
          CI: ${{ secrets.CI }}

      - name: Generate Prisma Client # Prisma 클라이언트 생성
        run: pnpm prisma generate # pnpm을 사용하여 Prisma 클라이언트 생성
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # 데이터베이스 URL

      - name: Build Project # NestJS 빌드
        run: pnpm build # pnpm을 사용하여 빌드
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }} # 환경 변수 설정
          CI: ${{ secrets.CI }} # CI 환경 변수 설정

      - name: Upload Build Artifact # 빌드 결과물 업로드
        uses: actions/upload-artifact@v4 # actions/upload-artifact 레포지토리의 v4 버전 사용
        with:
          name: build # 업로드할 파일 이름
          path: |
            dist
            package.json
            pnpm-lock.yaml
            prisma
            node_modules/.prisma/client

      - name: Configure SSH # SSH 설정
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }}
          chmod 600 ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }}
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Validate Environment Variables
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL is not set"
            exit 1
          fi
          # 다른 필수 환경 변수들도 검증
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "EC2_HOST is not set"
            exit 1
          fi
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "EC2_SSH_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DEPLOY_VERIFY_KEY }}" ]; then
            echo "DEPLOY_VERIFY_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.EC2_USERNAME }}" ]; then
            echo "EC2_USERNAME is not set"
            exit 1
          fi
          if [ -z "${{ secrets.EC2_KEY_PAIR_TYPE }}" ]; then
            echo "EC2_KEY_PAIR_TYPE is not set"
            exit 1
          fi
          if [ -z "${{ secrets.GPG_PASSPHRASE }}" ]; then
            echo "GPG_PASSPHRASE is not set"
            exit 1
          fi
          if [ -z "${{ secrets.NODE_ENV }}" ]; then
            echo "NODE_ENV is not set"
            exit 1
          fi

      - name: Mask Sensitive Variables
        run: |
          echo "::add-mask::${{ secrets.DATABASE_URL }}"
          echo "::add-mask::${{ secrets.EC2_HOST }}"
          echo "::add-mask::${{ secrets.EC2_SSH_KEY }}"
          echo "::add-mask::${{ secrets.DEPLOY_VERIFY_KEY }}"
          echo "::add-mask::${{ secrets.EC2_USERNAME }}"
          echo "::add-mask::${{ secrets.EC2_KEY_PAIR_TYPE }}"
          echo "::add-mask::${{ secrets.GPG_PASSPHRASE }}"
          echo "::add-mask::${{ github.sha }}"

      - name: Create env file # 환경 변수 암호화
        run: |
          echo "::add-mask::$(echo DATABASE_URL=${DATABASE_URL})"
          echo "DATABASE_URL=${DATABASE_URL}" | gpg --symmetric --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" > .env.production.gpg
          scp -i ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }} .env.production.gpg ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/backend/
          echo "::add-mask::$(cat .env.production)"

      - name: Setup PM2 Config
        run: |
          echo "module.exports = {
            apps: [{
              name: 'snack25-be',
              script: 'dist/main.js',
              instances: 'max',
              autorestart: true,
              watch: false,
              max_memory_restart: '1G',
              env: {
                NODE_ENV: 'production'
              }
            }]
          };" | gpg --symmetric --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" > ecosystem.config.js.gpg

      - name: Configure Environment
        run: |
          # 환경 변수 파일 생성 시 마스킹
          echo "::add-mask::$(echo DATABASE_URL=${DATABASE_URL})"
          echo "DATABASE_URL=${DATABASE_URL}" >> .env.production

          # SSH 키 마스킹
          echo "::add-mask::$(cat ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }})"

          # 배포 경로 마스킹
          echo "::add-mask::~/backend"

      - name: Backup current deployment # 처음 배포 시 백업 없으면 skip
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ~/backend && \
          if [ -d dist ] || [ -d node_modules ]; then \
            backup_file=\"backup-\$(date +%Y%m%d_%H%M%S).tar.gz\" && \
            echo \"::add-mask::$backup_file\" && \
            tar -czf \$backup_file dist node_modules || true; \
          else \
            echo \"No existing deployment to backup\" \
          fi"

      - name: Deploy to EC2 # EC2로 배포
        timeout-minutes: 10 # 타임아웃 시간 10분
        env:
          HOST: ${{ secrets.EC2_HOST }} # EC2 호스트 주소
          USERNAME: ${{ secrets.EC2_USERNAME }} # EC2 유저 이름
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # EC2 SSH 개인 키
          KEY_PAIR_TYPE: ${{ secrets.EC2_KEY_PAIR_TYPE }} # 키 페어 타입
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # 데이터베이스 URL
          DEPLOY_VERIFY_KEY: ${{ secrets.DEPLOY_VERIFY_KEY }} # 배포 검증 키
          GIT_COMMIT_SHA: ${{ github.sha }} # GitHub 커밋 SHA
        run: |
          echo "Deploying to $HOST"
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "df -h"
          echo "Starting deployment to EC2..."
          echo "Creating .env.production file..."
          echo "DATABASE_URL=${DATABASE_URL}" > .env.production
          scp -i ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }} -r dist package.json pnpm-lock.yaml prisma ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/backend/
          scp -i ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }} .env.production ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/backend/
          scp -i ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }} ecosystem.config.js.gpg ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/backend/
          ssh -i ~/.ssh/id_${{ secrets.EC2_KEY_PAIR_TYPE }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ~/backend && \
            # Node.js 프로세스 종료
            pm2 delete all || true && \
            # pnpm는 이미 설치되어 있으므로 설치하지 않음
            # 의존성 설치
            pnpm install --prod && \
            # Prisma 마이그레이션
            pnpm prisma generate && \
            pnpm prisma migrate deploy && \
            # PM2로 애플리케이션 시작
            pm2 start ecosystem.config.js --env production" # PM2로 애플리케이션 시작
          echo "::add-mask::$(pm2 list)"  # PM2 프로세스 목록 마스킹

      - name: Rollback on Failure # 배포 실패 시 롤백
        if: failure()
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ~/backend && \
          if ls backup-*.tar.gz 1> /dev/null 2>&1; then
            echo "Backup found, restoring..."
          pm2 delete snack25-be || true && \
            tar -xzf backup-*.tar.gz && \
            pm2 start ecosystem.config.js --env production
            echo "Rollback complete."
          else
            echo "No backup found, cannot rollback."
          fi"

      - name: Verify Deployment
        run: |
          max_retries=10  # 재시도 횟수 증가
          retry_interval=20  # 간격 증가
          for i in $(seq 1 $max_retries); do
            response=$(curl -s -w "%{http_code}" -H "X-Deploy-Key: ${{ secrets.DEPLOY_VERIFY_KEY }}" http://${{ secrets.EC2_HOST }}:4000/health)
            status_code=${response: -3}
            body=${response:0:${#response}-3}

            if [ "$status_code" = "200" ] && [ "$(echo $body | jq -r '.version')" = "${{ github.sha }}" ]; then
              echo "배포가 성공적으로 완료되었습니다."
              exit 0
            fi
            echo "재시도 중... ($i/$max_retries)"
            sleep $retry_interval
          done
          echo "배포 검증 실패"
          exit 1

      - name: Health Check
        run: |
          curl -f http://${{ secrets.EC2_HOST }}:4000/health || exit 1

permissions:
  contents: read # 레포지토리 내용 읽기 권한
  deployments: write # 배포 권한
  id-token: write # OIDC 인증을 위해 추가 필요

concurrency:
  group: production_environment # 동시성 그룹 설정
  cancel-in-progress: false # 진행 중인 작업 취소 여부
